# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Feiyue Zhang
description: > # this means to ignore newlines until "baseurl:"
repository: https://github.com/feiyue-z/feiyue-z.github.io
baseurl: # the subpath of your site, e.g. /blog
url: https://feiyue-z.github.io/  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Feiyue Zhang
email: feiyue_zhang@brown.edu

navigation:
  - text: Home
    url: /
  - text: Projects
    url: /projects

projects:
  - name: Game Engine
    description: A 2D game engine made with Java and a demo game to show it capabilities.
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
  - name: Real-time 3D Rendering
    description: Rendering 3D images with Phong illumination model in OpenGL.
    link: https://github.com/sobolevn/awesome-cryptography
    image: https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg
  - name: Search Engine
    description: A simple search engine built from the ground up in Python.
    link: https://github.com/sobolevn/ecto_autoslug_field
  - name: Online Shop
    description: A web application using Spring Boot, React, and MySQL.
    link: https://github.com/sobolevn/django-split-settings

social:
  - service: github
    username: feiyue-z
    link: https://github.com/feiyue-z
